name = "training-log"
type = "javascript"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
vars = { VITE_SUPABASE_URL = "https://nusfjbqxuqxynpdyqbcm.supabase.co", VITE_SUPABASE_ANON_KEY = "sb_publishable_lspCyoV98jMHB5_k3_L5qw_D3fQqCV5", VITE_AI_PROVIDER = "cloudflare", VITE_CLOUDFLARE_ACCOUNT_ID = "9071c4f96e81d14a58b223d020644dbc", VITE_CLOUDFLARE_API_TOKEN = "8TI8RSG0RjJic_qKnl2znP6VXmJEf84Nzb5Yblq3" }

